# Generated by Django 4.0.4 on 2022-06-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_amount',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
    ]
